apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-agent-engine
  source:
    type: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-agent-engine.git
      dir: /
spec:
  info:
    title: Serverless Agent Engine
    version: 1.0.0
    actuationTool:
      type: Terraform
      version: ">= 1.3.0"
    description:
      tagline: A serverless, event-driven agent engine on Google Cloud.
      detailed: This module deploys a serverless agent engine using Cloud Run, triggered by messages on a Pub/Sub topic via an Eventarc trigger. It includes a dedicated service account and the necessary IAM bindings for secure operation.
    documentations:
      - title: README
        url: ./README.md
  interfaces:
    variables:
      - name: name
        description: The base name for all resources created by this module.
        type: string
        default: agent-engine
        required: true
      - name: location
        description: The GCP region to deploy the Agent Engine resources into.
        type: string
        default: us-central1
        required: true
      - name: project_id
        description: The GCP project ID where the Agent Engine and its resources will be deployed. If not provided, the provider project is used.
        type: string
        default: null
        required: false
      - name: agent_container_image
        description: The container image to be used for the Agent Engine's Cloud Run service.
        type: string
        default: gcr.io/cloudrun/hello
        required: true
      - name: cloud_run_service_params
        description: Configuration parameters for the Cloud Run service, including scaling, concurrency, and environment variables.
        type: object
        default: {}
        required: false
      - name: service_account_create
        description: A boolean flag to control the creation of a new service account for the Agent Engine. If false, `service_account_email` must be provided.
        type: bool
        default: true
        required: true
      - name: service_account_email
        description: The email of an existing service account to be used by the Agent Engine. Required if `service_account_create` is false.
        type: string
        default: null
        required: false
      - name: grant_eventarc_sa_user_role
        description: If true, grants the Eventarc service account the 'Service Account User' role on the agent's service account, which is required for Eventarc to impersonate the service account to invoke the Cloud Run service.
        type: bool
        default: true
        required: true
      - name: grant_pubsub_token_creator_role
        description: If true, grants the Pub/Sub service account the 'Service Account Token Creator' role on the agent's service account, which is required for Eventarc to invoke Cloud Run with authentication.
        type: bool
        default: true
        required: true
    variableGroups:
      - name: General Configuration
        description: Basic settings for the agent engine deployment.
        variables:
          - name
          - location
          - project_id
      - name: Cloud Run Service Configuration
        description: Settings for the core Cloud Run service.
        variables:
          - agent_container_image
          - cloud_run_service_params
      - name: Service Account Configuration
        description: Configure the service account for the agent engine.
        variables:
          - service_account_create
          - service_account_email
      - name: IAM and Permissions
        description: Control IAM bindings managed by the module.
        variables:
          - grant_eventarc_sa_user_role
          - grant_pubsub_token_creator_role
    outputs:
      - name: cloud_run_service_id
        description: The fully qualified ID of the created Cloud Run service.
      - name: cloud_run_service_uri
        description: The publicly invokable URI of the Agent Engine's Cloud Run service.
      - name: pubsub_topic_id
        description: The fully qualified ID of the Pub/Sub topic used as the task queue for the Agent Engine.
      - name: service_account_email
        description: The email address of the service account used by the Agent Engine.
  requirements:
    roles:
      - level: project
        roles:
          - roles/run.admin
          - roles/pubsub.admin
          - roles/eventarc.admin
          - roles/iam.serviceAccountAdmin
          - roles/serviceusage.serviceUsageAdmin
          - roles/iam.serviceAccountUser
          - roles/iam.serviceAccountTokenCreator
          - roles/secretmanager.admin
    services:
      - iam.googleapis.com
      - cloudresourcemanager.googleapis.com
      - pubsub.googleapis.com
      - run.googleapis.com
      - eventarc.googleapis.com
      - secretmanager.googleapis.com
